chatChannels:
  global:
    symbol: "!"
    prefix: "[GLOBAL]"
  trade:
    symbol: "."
    prefix: "[TİCARET]"
  local:
    prefix: "[LOCAL]"
  region:
    prefix: "[REGION]"
    allowed-regions:
      - region1
      - region2
    region-command: "say {player} bölgeye girdi!"
