# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
#
# aeChannels ((.gg/toprakates for support and suggestions))
#
# . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

chatChannels:

  global:
    symbol: "!"
    prefix: "[GLOBAL]"
  trade:
    symbol: "."
    prefix: "[TİCARET]"
  local:
    prefix: "[LOCAL]"
  region:
    prefix: "[REGION]"
    allowed-regions:
      - ornek_bolge1
      - ornek_bolge2
    region-command: "say {player} bölge sohbetine girdi!"

  groupPrefixes:
    default: "&7"
    vip: "&a"
    mvip: "&b"
    mvipplus: "&3"
    blokvip: "&6"
    yayinci: "&d"
    youtuber: "&c"
    moderator: "&5"
    takim: "&e"
    yonetici: "&4"

mention:
  enabled: true
  message: "&e@{player} seni etiketledi!"
  sound:
    enabled: true
    name: "ENTITY_PLAYER_LEVELUP"
    volume: 1.0
    pitch: 1.0

