name: aeChannels
main: me.toprak.aechannels.AEChannels
version: 1.0
api-version: 1.21
author: toprakates
description: Dünya ve bölge bazlı sohbet kanalları, özel prefix ve WorldGuard entegrasyonu ile.
website: https://github.com/toprakatess1/aeChannels
depend: [WorldGuard]
